### ISSUE TITLE
Provide support for Redact Secure Websites

### ISSUE THREAD

**Issue by scrumit** [xyproto/algernon#100]
This product is just coming out of an accelerator that I read about. [How it works](https://redact.ws/how-it-works). 

It would need a client adding to Algernon that separately access secrets. So secure websites don't actually have the secrets.

I can see even more value if the secure client can access multiple Redact Stores. This would allow services that provide secure collaboration between organisations. 

I'll investigate more. Now Teal is in place (congratulations),  I'll install Algernon again.

**Comment by ajpauwels** [comment]
Hi all, I'm Alexandre Pauwels, one of the lead developers on Redact.

Happy to discuss integration with Algernon, although I'm not sure there has to be any particular integration? The Redact client runs on the local machine, and iframes make requests to it; to use Redact with Algernon, one would just need to place iframes in their generated HTML.

**Comment by xyproto** [comment]
Thanks for the comment @ajpauwels. If Algernon can already be used together with Redact, that's great.

@scrumit I assume this means that this feature request can be closed?

**Comment by scrumit** [comment]
Alexandre explained it to me.

Still looking forward to an API version.
