### ISSUE TITLE
json() will drop all data in the table which is converting to json

### ISSUE THREAD

**Issue by linkerlin** [xyproto/algernon#107]
In Algernon's REPL:

```lua
lua> json({a=1})
{}
```
#106

**Comment by linkerlin** [comment]
I have read the code , and I find :
```go
		// Convert the Lua table to a map that can be used when converting to JSON (map[string]interface{})
		mapinterface := gluamapper.ToGoValue(table, gluamapper.Option{
			NameFunc: func(s string) string {
				return s
			},
		})
```
NOTICE that：
`to JSON (map[string]interface{})`
In the early ,the REPL report:
`ERRO[0356] json: unsupported type: map[interface {}]interface {} `

**Comment by linkerlin** [comment]
![image](https://user-images.githubusercontent.com/37062/177027814-8f472f4b-491c-4258-8ba7-2d11247bbacb.png)
the `map[interface {}]interface {}` is from here 👆

**Comment by linkerlin** [comment]
![image](https://user-images.githubusercontent.com/37062/177028396-e1209fe3-6ae9-46bd-ba64-40f680a0b6e2.png)
I fixed the bug by changed `map[interface{}]interface{}` to `map[string]interface{}`

**Comment by linkerlin** [comment]
By the way, revert 
https://github.com/xyproto/algernon/commit/86c3a7c458770c07fc644467959989ccee844384

**Comment by xyproto** [comment]
Thanks for reporting, I'm able to reproduce the issue.

**Comment by xyproto** [comment]
Thanks! Reverting 86c3a7c458770c07fc644467959989ccee844384 and applying the patch worked.

However, I already had a fork of gluamapper + gopher-lua that had the suggested changes, so I just switched (back) to those. They were removed some time ago because I mistakenly thought that they were no longer needed.

These two now works again, in `main`:

```
json {a=1}
json {a={b=100}}
```

Thanks for reporting and patching!

**Comment by tooolbox** [comment]
@xyproto I wonder how easy it would be to set up CI/GH Actions to execute Lua scripts with Algernon and check the output, so things like this as well as perhaps https://github.com/xyproto/algernon/issues/106 and anything similar can be checked and defended against regressions?

**Comment by xyproto** [comment]
Good suggestion. This should be feasable, either with `go test` or by fetching the result from Algernon with `curl` at test time.
