### ISSUE TITLE
trouble with auto-refresh

### ISSUE THREAD

**Issue by automaticgiant** [xyproto/algernon#11]
when trying various combinations of options, unable to get auto-refresh to work.
Safari gives:
`[Error] Refused to connect to http://127.0.0.1:5553/fs because it does not appear in the connect-src directive of the Content Security Policy.`
Chrome gives:
`localhost/:1 Uncaught DOMException: Failed to construct 'EventSource': Refused to connect to 'http://localhost:5553/fs' because it violates the document's Content Security Policy.
    at http://localhost:3000/:1:922`

**Comment by automaticgiant** [comment]
looks like i have to use `--noheaders`. got lucky discovering this.
not sure if documentation or code bug...

**Comment by xyproto** [comment]
Hi, thanks for reporting! Will look into this. The default headers are probably too strict for the Server-Sent Events that are used for detecting file changes.

**Comment by xyproto** [comment]
Which version of Algernon is this for?

This check has been in place in `handlers.go` since version 1.3.1:

```go
	if !ac.autoRefreshMode {
		w.Header().Set("X-XSS-Protection", "1; mode=block")
		w.Header().Set("X-Content-Type-Options", "nosniff")
		w.Header().Set("X-Frame-Options", "SAMEORIGIN")
		w.Header().Set("Content-Security-Policy", "connect-src 'self'; object-src 'self'; form-action 'self'")
	}
```

**Comment by xyproto** [comment]
If you are using Homebrew on macOS, simply upgrading algernon should fix the issue.

If you are on Windows, I made a new binary release [here](https://github.com/xyproto/algernon/releases/tag/v1.4.1-win8-64) of version 1.4.1.
