### ISSUE TITLE
low ulimit on macOS

### ISSUE THREAD

**Issue by d4z3x** [xyproto/algernon#118]
Following the sample invocation on a Mac M1 Pro (macOS Monterey 12.5), gives the following error of too many files open:

```bash
git/algernon $ ./welcome.sh
Try editing the markdown file in "samples" directory and see the
results instantly in the browser at http://localhost:3000/
	Algernon
	1.14.0
	Web Server

-> serverconf.lua
sitename="Sample Site"
FATA[0000] open /Users/XXX/git/algernon/samples/react_tut/tutorial20/comments: too many open files`

**Comment by xyproto** [comment]
Ah, yes, the default number of files that can be open at the same time ("ulimit") on macOS is very low.

Try either removing `--autorefresh` from `welcome.sh` or try one of the answers here:

https://apple.stackexchange.com/questions/32235/how-to-properly-increase-a-ulimit-n-limits
