### ISSUE TITLE
Markdown not parsing reference links

### ISSUE THREAD

**Issue by scrumit** [xyproto/algernon#12]
I added a second place with same link, so changed it to a reference link:

```
[ROWeb]:(http://algernon.roboticoverlords.org/)
```

And what Algernon parsed that to was:

```
/Users/buildslave/Library/Containers/org.roboticoverlords.algernon/Data/Documents/Algernon/(http:/algernon.roboticoverlords.org/)
```

**Comment by scrumit** [comment]
adding issue to blackfriday, too.

**Comment by xyproto** [comment]
Thanks for reporting! Will look into it.

**Comment by xyproto** [comment]
I'm unable to reproduce the issue here. Could you please provide a small `.md` file that demonstrates the issue?

Also, which version of `algernon` is this, is it the latest one from homebrew?

**Comment by scrumit** [comment]
I'm using two versions. The first is from the Mac store, the version of Algernon according to _get info_ is 1.4 and according to the container.plist is 35.

On this Mac I am using the home-brew version and that is 1.4.3

Attached a ZIP of the index.md file that exhibits the problem.

[index.md.zip](https://github.com/xyproto/algernon/files/1082484/index.md.zip)

**Comment by xyproto** [comment]
Thanks for the `index.md` file! I'm able to reproduce the issue now.

**Comment by xyproto** [comment]
When converting index.md with `pandoc index.md -o index.html` the output is:

```
<p>title: Markdown</p>
<h2 id="test-of-ref-link">Test of ref link</h2>
<p>This is a <a href="http://algernon.roboticoverlords.org/">direct link to the RO page</a></p>
<p>This is <a href="" title="http://algernon.roboticoverlords.org/">an indirect link</a></p>
```

The second link URL ends up in the link title. Do you know of any utilities or libraries that converts the ref links as expected?

I'll read the Markdown spec(s) closely and see what I can find.

**Comment by scrumit** [comment]
I use markdown purely for documentation.  it appears dillinger and Quoda
are also broken in the same way.

I use Macdown on Mac,

```
<p>title: Markdown</p>
<h2 id="toc_0">Test of ref link</h2>
<p>This is a <a href="http://algernon.roboticoverlords.org/">direct link to
the RO page</a></p>
<p>This is <a href="(http://algernon.roboticoverlords.org/)">an indirect
link</a></p>
```
minimalist material markdown on Chrome/Chromebook
```
<p>title: Markdown</p>
<h2>Test of ref link</h2>
<p>This is a <a href="http://algernon.roboticoverlords.org/">direct link to
the RO page</a></p>
<p>This is <a href="(http://algernon.roboticoverlords.org/)">an indirect
link</a></p>
```

and Dillinger on browser
```
<p>title: Markdown</p>
<h2><a id="Test_of_ref_link_2"></a>Test of ref link</h2>
<p>This is a <a href="http://algernon.roboticoverlords.org/">direct link to
the RO page</a></p>
<p>This is <a href="(http://algernon.roboticoverlords.org/)">an indirect
link</a></p>
```
I can't get the HTML from quoda because I only have the free version on
Android.

**Comment by dolanor** [comment]
Got bitten by this one also (not on algernon, on gogs though), but just to give the link to the spec: https://daringfireball.net/projects/markdown/syntax#link

(btw, I tried in github, doesn't seem to work either…)

**Comment by scrumit** [comment]
Ah, on reading the spec closely I note this:

```
* followed by a colon;
* followed by one or more spaces (or tabs);
* followed by the URL for the link;
```

So, no space could be messing it up. Also:

``` The link URL may, optionally, be surrounded by angle brackets:

[id]: <http://example.com/>  "Optional Title Here"
```

Nowhere does it suggest surrounding the URL in quotes. I'll investigate further.

**Comment by xyproto** [comment]
I am glad things are in order. Thanks for caring enough to fill a bug report. Cheers!
