### ISSUE TITLE
lua to wasm

### ISSUE THREAD

**Issue by gedw99** [xyproto/algernon#128]
https://www.fermyon.com/wasm-languages/lua

so can run on a server with sandboxing...

Its just an idea ... might not suit oyur needs but i use it.

---
@xyproto 

BTW alernon does not support updating the GUI as the files change or HTMX aspects for updating parts of the page as the files change ?

**Comment by xyproto** [comment]
Thanks for the suggestion. The linked page has several links to several Lua/WASM-related project. Which one did you have in mind?

**Comment by gedw99** [comment]
I tried to get it working with golang but it does not so will close this .
