### ISSUE TITLE
.alg files are persisted to /tmp

### ISSUE THREAD

**Issue by Dialga** [xyproto/algernon#132]
I tried the example .alg app and thought that files were being served directly from the archive, but I have found this is not the case.
If this is by design then can the .alg section be expanded to mention that they are just zip archives extracted to the temp folder and its contents left as is after shutting down the server, noting that it may have potential security implications for private applications.

**Comment by xyproto** [comment]
@Dialga Thanks for reporting! I agree.

I will update the documentation and also consider this as a feature request for extracting to memory instead.

**Comment by xyproto** [comment]
Algernon is now extracting them to `/dev/shm` instead, if possible.
