### ISSUE TITLE
question: There is an documentation/reference of al

### ISSUE THREAD

**Issue by doesnmisclown** [xyproto/algernon#137]
Examples is good but i cant understand all supported methods of lua integration, etc

**Comment by xyproto** [comment]
Thanks for the question!

Which format would be most useful? A large Markdown file, a PDF or a static web page?

**Comment by doesnmisclown** [comment]
To be honest i don't know. Large md file seems be laggy (like python or matrix docs), pdf may be variant but afaik nobody uses it, and what does mean "static page"?

**Comment by xyproto** [comment]
A static web page is the opposite of dynamic. It is when a web page is more like a brochure with information and less like an application.

**Comment by doesnmisclown** [comment]
Okay, may be static page

**Comment by xyproto** [comment]
Please test if this tutorial is helpful:

https://github.com/xyproto/algernon/blob/main/TUTORIAL.md

**Comment by doesnmisclown** [comment]
at begin ok
