### ISSUE TITLE
Is there a plan to support QUIC?

### ISSUE THREAD

**Issue by JermineHu** [xyproto/algernon#14]
**Algernon is a great server and expects it to support QUIC！Find some reference code from GitHub**

https://github.com/lucas-clemente/quic-go

https://github.com/devsisters/goquic

https://github.com/mholt/caddy

**Comment by xyproto** [comment]
Thanks for the suggestion, I will consider adding QUIC support.

**Comment by JermineHu** [comment]
@xyproto **I will continue to pay attention to this project, I believe it will become better and better !**

**Comment by xyproto** [comment]
Added initial support for QUIC, please test. :)
