### ISSUE TITLE
Automatic ACME / LetsEncrypt

### ISSUE THREAD

**Issue by ptman** [xyproto/algernon#141]
The best feature of caddy

- https://github.com/caddyserver/certmagic
- https://pkg.go.dev/golang.org/x/crypto/acme/autocert

**Comment by xyproto** [comment]
Thanks for the feature request. Algernon already has a `--letsencrypt` flag that uses `certmagic`.

Were you thinking of something similar to that, or a new feature that Algernon does not yet have?

**Comment by ptman** [comment]
I couldn't find it mentioned in the readme

**Comment by xyproto** [comment]
I updated the documentation. Please check if it makes sense.

**Comment by ptman** [comment]
thank you
