### ISSUE TITLE
Forbid access to files

### ISSUE THREAD

**Issue by alpharde** [xyproto/algernon#149]
Requesting a option to disallow access to certain files, returning 404 or 403 and to hide such files from the directory index.

**Comment by xyproto** [comment]
Thanks for reporting! What would be the ideal way to configure something like this? Read `.ignore`/`_ignore` files if they are present, and then don't list the files covered by the globs/patterns in such files?

**Comment by xyproto** [comment]
Added support for `.ignore` files on non-Windows platforms, and `ignore.txt` on Windows.
