### ISSUE TITLE
server port changed

### ISSUE THREAD

**Issue by scrumit** [xyproto/algernon#15]
The port used for the Algernon mac application has changed from 3000 to 4000 and I can't change it back. 

I know it happened because I started Algernon from the command line once. Now I can't change it back. I'm sure I can dig around the code but it's easier to ask. Sorry.

**Comment by xyproto** [comment]
Adding 3000 to the command line should remedy this (for the latest version of Algernon):

    algernon /some/directory 3000

I will look into what may have changed. Thanks for reportng.
