### ISSUE TITLE
Can markdown latex be supported

### ISSUE THREAD

**Issue by xjl456852** [xyproto/algernon#150]
Now the algernon not support markdown latex.
![image](https://github.com/xyproto/algernon/assets/8008097/44e138e3-2577-4eef-b660-63b2570e05c1)

Can markdown latex be supported
thank you!

**Comment by xyproto** [comment]
Thanks for the feature request! I will see if I can find a Go module that supports it.

**Comment by xyproto** [comment]
I added support for this.

If you clone the repo, build with "go build -mod=vendor" and then run `./welcome.sh` or `./welcome.bat` (depending on your system), then the "Mathematical Formulas" example demonstrates the use.

Please test.

**Comment by xjl456852** [comment]
I have tested the latest version. maybe cann't work. the table also can't work.
but when I delete any text block, latex can work , but the table always cann't work.

 the test.md

[test.md](https://github.com/user-attachments/files/15515215/test.md)

![image](https://github.com/xyproto/algernon/assets/8008097/2d230d9a-f5ea-4601-bbc8-0eef84b092be)

thank you .

**Comment by xyproto** [comment]
It is the text at the end that stops the formulas from working, and not the tables:

    ```test
    any text
    ```

I am in the process of figuring out why this is. Perhaps it is related to how MathJax works.

**Comment by xyproto** [comment]
There is a bug in https://github.com/xyproto/splash where it is confused if there is both blocks of code and also MathJax output.

**Comment by xyproto** [comment]
I fixed this issue in the `main` branch. Please test.

**Comment by xyproto** [comment]
Thanks for the feedback! I changed the MathJax rendering to output SVG instead of HTML, which I hope will fix the woff font issue.

Why the borders are missing is a mystery to me. They look fine here:

<img width="1238" alt="bilde" src="https://github.com/xyproto/algernon/assets/52813/d656d491-e3d0-4f57-9697-4cf7dd55a3f6">

I made the borders for the default theme just a bit thicker, just in case it makes it work on your end.

Please test. Thank you.

**Comment by xjl456852** [comment]
The formulas are now displayed correctly, but the table still has no borders.
![image](https://github.com/xyproto/algernon/assets/8008097/7c845639-f733-481d-9b48-3878656f7849)

**Comment by xyproto** [comment]
That is curious.

Are you opening the markdown file with `algernon -m file.md` and then viewing the result in a browser like Firefox or Chromium?

Which OS, Browser and command for launching Algernon are you using?

**Comment by xjl456852** [comment]
My OS is windows 11.
My browser is Edge.
When I put the test.md file in to the algernon main directory, the table has borders. but When I put the test.md file in to the algernon/samples directory, the table has no borders.

I used double click algernon.exe , double click welcome.bat, algernon -m file.md, and algernon -m dir\file.md  to test it.

For example I used double click algernon.exe  to start server:
Test.md in the algernon main directory:
![image](https://github.com/xyproto/algernon/assets/8008097/f811363d-00d8-49da-bcad-a7b1e9009a73)

Test.md in the algernon/samples directory:
![image](https://github.com/xyproto/algernon/assets/8008097/47dd587b-4fc3-48cb-bd0e-51b4991c400d)


# I found anther bug.
I modified the test.md to test1.md.
When the md has two same picture links, `algernon -m file.md` this command can't to used, it can't open browser, and the process can't to load. (Using this command to run the test.md is normal).
![image](https://github.com/xyproto/algernon/assets/8008097/a8e4256a-1710-43af-9a37-61e496f9fd9d)

You can download this test1.zip, and unzip it to test `algernon -m file.md` command.
[test1.zip](https://github.com/user-attachments/files/15558864/test1.zip)

**Comment by xjl456852** [comment]
I updated the test1.zip file
