### ISSUE TITLE
Need to explicitly convert ac.limitRequests to float64 for engine/handlers.go and engine/luahandler.go

### ISSUE THREAD

**Issue by zoybai** [xyproto/algernon#16]
engine/handlers.go:432:37: cannot use ac.limitRequests (type int64) as type float64 in argument to tollbooth.NewLimiter
engine/luahandler.go:47:38: cannot use ac.limitRequests (type int64) as type float64 in argument to tollbooth.NewLimiter

**Comment by xyproto** [comment]
Thanks for reporting, will look into this!

Does this happen also when the repository and all git submodules are checked out (git clone --recursive)?

**Comment by zoybai** [comment]
We haven't test git clone --recursive yet. This happened when we did "go get ."

**Comment by xyproto** [comment]
Will try to reproduce the issue from a blank and pristine go 1.10 installation.

**Comment by xyproto** [comment]
`go get github.com/xyproto/algernon` worked as a charm with both Ubuntu 18.04 + go 1.9.4 and Arch Linux + go 1.10.

I'm unable to reproduce the issue.

More information is needed:

* Which system are you on?
* Which version of go do you use? (`go version`)
* Do you have old source code checked out in `$GOPATH` and/or `~/go`?

Please try removing `$GOPATH` or `~/go` and try `go get github.com/xyproto/algernon` again.

**Comment by zoybai** [comment]
Version:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"
Linux d-127 4.13.0-32-generic #35-Ubuntu SMP Thu Jan 25 09:13:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
go version devel +816154b065 Tue Feb 13 07:01:26 2018 +0000 linux/amd64
Algernon 1.9

Probably the problem is development version of go.

**Comment by zoybai** [comment]
https://github.com/didip/tollbooth/commit/b4c82f72a259761663881f8077f326f11e215f8d#diff-007503cfdd6314e37d40f96773bf2e05

github.com/didip/tollbooth/tollbooth.go: 57 max float64

github.com/didip/tollbooth has changed max rate from int64 to float64 on Jan 26 2018 in version 4.0.0

Somehow our golang used the latest tollbooth:

commit c95eaa3ddc98f635a91e218b48727fb2e06613ea (HEAD -> master, tag: v4.0.0, origin/master, origin/HEAD)
Merge: b65680a b4c82f7
Author: Didip Kerabat <didipk@gmail.com>
Date:   Sun Feb 4 20:54:54 2018 -0800

    Merge pull request #60 from anopheles/master

    added floating point limit support

commit b4c82f72a259761663881f8077f326f11e215f8d
Author: David Kaufman <david.kaufman@freiheit.com>
Date:   Fri Jan 26 10:27:36 2018 +0100

    added floating point limit support

**Comment by xyproto** [comment]
Hopefully a better solution for dependency management in Go will emerge from the Go developers or the Go community in the future.
