### ISSUE TITLE
How can i use CSS for Markdown files?

### ISSUE THREAD

**Issue by vodan** [xyproto/algernon#19]
Hello i really like algernon. But why are you using another css style with gcss why can you not use css?

**Comment by xyproto** [comment]
Hi, thanks for your interest in Algernon. :)

Here is one way of using CSS with Markdown: [Markdown + CSS](https://github.com/xyproto/algernon/tree/master/samples/mdcss).

Do you think it would also be a good idea if not only `style.gcss` was used automatically, but also `style.css`?

I'm thinking about maybe removing the automatic use of `style.gcss`, but it might be nice to keep for backward compatibility.

**Comment by vodan** [comment]
Hi,
As it would be easy to distinguish between gcss or css file i would use your existing "--theme" argument, and extend it to accept files.
The Problem i had with automatic use of gcss is that it is only used for the current folder. I have a folder structure of multiple markdown files connected via links which i normally read via vim. If i need to share something i used pandoc to just share one file.

with algernon i could share/and read myself the full collection in a browser. But therefore the use of default template css via commandline would be really nice.

So great work and keep going :+1:

**Comment by xyproto** [comment]
I see.

One solution is to add a `style.gcss` file with this content:

```
@import "style.css"
```

Then also have a `style.css` file in the same directory.

I will think some more about what the best solution for this would be. Perhaps using `style.css` if it exists is an acceptable solution.

**Comment by xyproto** [comment]
Added a sample here: https://github.com/xyproto/algernon/tree/master/samples/mdstyle

**Comment by xyproto** [comment]
Added support for detecting and using `style.css` files in the same way as `style.gcss`, in commit 5875d59cdf36405376d8618df1f85deaf857ba9c.

Also updated the Markdown + CSS samples in the [samples/mdstyle](https://github.com/xyproto/algernon/tree/7892fb73a90094bf2ef1aa2f91aa06b1a5ab99a0/samples/mdstyle) directory.

**Comment by vodan** [comment]
Thank for the solution. I had the time to test it and it works great now. Keep on coding.
