### ISSUE TITLE
Amber include and extend

### ISSUE THREAD

**Issue by EdVanDance** [xyproto/algernon#2]
Hi xyproto,

I really like this project, having fun with it atm.

I just stumbled across not being able to use Amber's import and extend features. It would be so helpful for the general layout.

Do you think it would be possible to enable them?

Greets,
Ed

__EDIT__: The error is:
```
Amber Error: Unable to import or extend nav in a non filesystem based parser.
```

**Comment by EdVanDance** [comment]
Just had a closer look, seems like `amber.CompileFile` does the trick.

Do you think this is a viable solution?

I tried with the patch below and it worked.

```patch
diff --git a/rendering.go b/rendering.go
index 38e87fc..a1ef6d9 100644
--- a/rendering.go
+++ b/rendering.go
@@ -152,7 +152,7 @@ func amberPage(w http.ResponseWriter, filename, luafilename string, amberdata []
     }

     // Compile the given amber template
-    tpl, err := amber.Compile(string(amberdata), amber.Options{true, false})
+    tpl, err := amber.CompileFile(filename, amber.Options{true, false})
     if err != nil {
         if DEBUG_MODE {
             prettyError(w, filename, amberdata, err.Error(), "amber")
```

**Comment by xyproto** [comment]
Hi, thanks for reporting! Glad you're having fun with Algernon.
I'll look at the suggested change and make it work. The disadvantage of using CompileFile is that the file is being read twice, but I'll see if I can find a way around this.
Cheers!

**Comment by xyproto** [comment]
Making the suggested changes in the master branch. :)

Please confirm that it works as expected.

**Comment by EdVanDance** [comment]
Hi xyproto,

it works. Thanks :)

But what's wrong about `amber.CompileFile`?
The double reading could be avoided by just trying to open the file instead of reading it in https://github.com/xyproto/algernon/blob/master/handlers.go#L50.

Or did I miss something?

**Comment by xyproto** [comment]
Another issue is that if `style.gcss` exists in the same directory, it is used as the stylesheet for the amber template, by linking to it. This *could* be done after the Amber template has been converted to HTML, but as it is, it's being done before the transform. Switching to `amber.CompileFile` would stop this from happening.

I'm glad it's working for you now!

**Comment by EdVanDance** [comment]
Ok I see. Do you think it makes sense to do this linking after compiling? If yes I could try to do that.

**Comment by xyproto** [comment]
Feel free to fork the project and give it a shot, of course. What I was thinking is that it would make sense to either do the stylesheet linking in the Amber data, before compiling -- or use a proper package for parsing and manipulating the DOM after the HTML has been generated. If you find a good Go package for parsing HTML to a tree and then inserting a link to the stylesheet, that could work. However, the result would be similar to the current situation, I think.

If your goal is to increase the speed, adding caching to file reads or caching compiled templates should give a boost. It's on my TODO-list, but I haven't implemented it yet.
