### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by Dialga** [xyproto/algernon#21]
Is is possible for you to add sqlite support?

**Comment by xyproto** [comment]
Thanks for reporting.

I wish to add support for SQLite, but I also want to keep the entire code base for Algernon in pure Go.

Right now, I don't know of any pure Go implementations that can read and write to SQLite database files.

However, Algernon supports BoltDB, which works a bit like SQLite, where the database is stored in a single file.

If a pure Go package that supports SQLite appears, please let me know, and I'll look into it.

**Comment by xyproto** [comment]
What is the specific use case you have in mind?

Is it just about storing to a file, or is it about being able to use a specific program for browsing or editing the salute database file after it has been written?

**Comment by Dialga** [comment]
Well this project mentions it support Mysql and Postgresql so perhaps it would be easier to add sqlite since it is serverless? If native support is not possible maybe as a lua module?

**Comment by xyproto** [comment]
None of the Lua modules I could find had support for Sqlite without using the C library.

If I can find either Lua code that can read and write to a Sqlite database without needing a C library, or a Go module that can read and write to Sqlite database without needing a C library, I will happily add support for it in Algernon.

Alternatively, I can find a way to add support for Sqlite through either the plugin system that comes with Go (which is supported on many platforms, but not on Windows), or through the plugin system that is currently in use in Algernon (which is not as fast as the standard Go plugin system, but cross platform).

A plugin could require the Sqlite C library, for the users that want that, while allowing Algernon to be compiled with `CGO_ENABLED=0`.

Having a way to add support for new databases, using the Go plugin system, is probably a good idea either way, so I'll look into adding this feature.

**Comment by xyproto** [comment]
Will implement this if a pure Go implementation that supports SQLite databases appears.

**Comment by Dialga** [comment]
Looks like there is now a pure Go version of SQLite https://gitlab.com/cznic/sqlite.

**Comment by xyproto** [comment]
Cool, I'll look into it. Thanks for the link!
