### ISSUE TITLE
tag 1.12.0 can no longer be built

### ISSUE THREAD

**Issue by bodsch** [xyproto/algernon#22]
I'm trying to rebuild my container in the middle of the same error again and again
```
env GO111MODULE=on go build -v -v
go: finding github.com/Joker/jade v0.7.0
go: finding github.com/kataras/iris v10.7.0+incompatible
go: github.com/Joker/jade@v0.7.0: unknown revision v0.7.0
go: github.com/kataras/iris@v10.7.0+incompatible: unknown revision v10.7.0
go: error loading module requirements
```
version `10.7.0` of `kataras/iris` is no longer available: https://github.com/kataras/iris/tags

Is there a quick fix (unfortunately I'm not so well versed in the go universe yet)?

**Comment by xyproto** [comment]
Thanks for reporting! I will try to reproduce the issue.

**Comment by xyproto** [comment]
Everything seems to work here, and the CI tests all pass: https://travis-ci.org/xyproto/algernon/builds

Please try:

    env GO111MODULE=off go build

**Comment by xyproto** [comment]
Both `master` and `1.12.0` built here, using `env GO111MODULE=off go build`.

I created a patch release tag: `1.12.1`. Does it work with that one?

**Comment by bodsch** [comment]
with `env GO111MODULE=off go build` the build runs perfektly

I will try `1.12.1` ...

**Comment by bodsch** [comment]
And with `1.12.1` the build runs without error.

Thanks for your help!

**Comment by xyproto** [comment]
Great, thanks for testing and thanks for creating docker-algernon!
