### ISSUE TITLE
Sample use of .zip/.alg

### ISSUE THREAD

**Issue by seansbox** [xyproto/algernon#27]
The readme references the ability to use .zip or .alg files, presumably to bundle your website content. Would it be possible to add a sample to the samples/ folder that utilizes this feature? Thanks!!

**Comment by xyproto** [comment]
Yes, that's a good idea, thanks for the suggestion.

**Comment by xyproto** [comment]
I added an example project here. It's a bit hacky, but it demonstrates `.alg` web applications:

https://github.com/xyproto/wercstyle
