### ISSUE TITLE
Login cookies clear after server restart

### ISSUE THREAD

**Issue by seansbox** [xyproto/algernon#28]
If a user has been logged in using SetUsernameCookie/SetLoggedIn but then we restart the algernon server, UsernameCookie no longer returns the logged in username. Is there a way around this? We'd like the server to retain logins (or at least re-use the set cookie) after reboot.

Thanks!!

**Comment by xyproto** [comment]
Hi, thanks for reporting.

The cookies are stored in the browser and the login state is stored in the database, so I'm thinking this could maybe be related to the database backend.

Which one are you using, Bolt, Redis, PostgreSQL or MariaDB/MySQL?

I'll try to reproduce the issue.

**Comment by seansbox** [comment]
Using the builtin Bolt.

**Comment by xyproto** [comment]
By default, the database is stored as `/tmp/bolt.db`, if nothing else is given. This works well for development, but when Algernon is running in "production mode", it is not optimal.

If you use the `--boltdb` flag to specify a database file that is not in `/tmp`, it should not be gone after reboot. The `/tmp` directory is cleared at reboot.

I'll add a warning when using the default database in `/tmp` when running Algernon in "production mode".

**Comment by seansbox** [comment]
I have specified a boltdb. The database itself is persistent. I'm using it to store other data that is retained between launches and that is working. Bust after a server restart and browser refresh, UsernameCookie() is empty. Here is my launcher:

#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

"$DIR/algernon" \
  --dir="$DIR/srv" \
  --boltdb="$DIR/data.bolt" \
  --key="$DIR/key.pem" \
  --cert="$DIR/cert.pem" \
  --dev \
  --autorefresh

**Comment by xyproto** [comment]
Thanks! I'll reproduce the issue and fix it.

**Comment by xyproto** [comment]
I don't think this is a BoltDB or database issue. I just double-checked by placing values in the database and restarting Algernon.

I think this may be related to cookie secrets and generation of random numbers:

https://github.com/xyproto/permissions2/blob/master/userstate.go#L204

It might be that the initial random seed needs to be stored somewhere, for the cookie to be recognized. I will investigate some more.

**Comment by xyproto** [comment]
I added a `--cookiesecret` flag that can be used for specifying the secret used by cookies.

When testing here, this solves the problem and makes login cookies persistent across server reboots.

Please test (the `master` branch).

**Comment by xyproto** [comment]
I also added the `CookieSecret` and `SetCookieSecret` Lua functions, that can be used for retrieving or setting the server-wide cookie secret setting.

**Comment by seansbox** [comment]
Brilliant! I will test today. This is a great solution.

**Comment by seansbox** [comment]
Confirmed this is resolved. Thanks!

**Comment by xyproto** [comment]
Thanks for testing!
