### ISSUE TITLE
SSL key location

### ISSUE THREAD

**Issue by Chaz6** [xyproto/algernon#29]
The example given (https://github.com/xyproto/algernon/blob/master/README.md#create-your-own-algernon-application-for-http2--https)  stores both the public and private ssl keys in the web root, which could be insecure if they are served to clients. It would be useful to provide information on how to store the keys in a different location.

**Comment by xyproto** [comment]
Thanks for reporting, I'll update the documentation.

**Comment by jamiesonbecker** [comment]
```
  --cert=FILENAME              TLS certificate, if using HTTPS.
  --key=FILENAME               TLS key, if using HTTPS.
```
