### ISSUE TITLE
jfile:get() cannot handle non-string fields

### ISSUE THREAD

**Issue by KonradMagnusson** [xyproto/algernon#3]
```
Algernon 0.87
Ready
lua> jf = JFile("test.json")
lua> print(tostring(jf))
{
  "desc": "Hello World!",
  "ping": 50,
  "status": true
}
lua> jf:get("desc")
Hello World!
lua> jf:get("ping")

lua> jf:get("status")

lua> 
```
Perhaps some form of casting is needed in jnodeGetNode()..?

**Comment by xyproto** [comment]
Thanks for reporting. Will fix!

**Comment by xyproto** [comment]
Modified `get` so that it returns the JSON value. Also added `getstring` and `getnode`.

Hope it works for you now! :) Please test.

**Comment by KonradMagnusson** [comment]
Works like a charm! Thanks!
I'm absolutely loving this project :)
