### ISSUE TITLE
panic: qtls.ClientSessionState not compatible with tls.ClientSessionState on MacOS 10.14.4 and go 1.11.4

### ISSUE THREAD

**Issue by tomcam** [xyproto/algernon#30]
When I tried to run Algernon I got this error: panic: qtls.ClientSessionState not compatible with tls.ClientSessionState. Seems to compile fine under Go 1.11.4.

Steps to reproduce:
```
$ go get -u github.com/xyproto/algernon
$ cd xyproto/algernon
$ env GO111MODULE=on go build
$ ./algernon -e
```
Result:
```
panic: qtls.ClientSessionState not compatible with tls.ClientSessionState

goroutine 1 [running]:
github.com/lucas-clemente/quic-go/internal/handshake.init.0()
	/Users/tom/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.0/internal/handshake/unsafe.go:20 +0x113

```
System: 2018 iMac running MacOS 10.14.4 with plenty of free RAM and disk space.

Can't wait to give Algernon a try!

**Comment by xyproto** [comment]
Algernon now requires Go 1.12 or later to compile.

If you're on Go 1.11, the `go111` branch should work.
