### ISSUE TITLE
Add HTTP client function (GET/POST/etc.)

### ISSUE THREAD

**Issue by seansbox** [xyproto/algernon#33]
Would it be possible to add a function inside of Lua for http GET, POST, etc.? This could be used for:

- building a CORS proxy (pass through requests)
- building OpenID Connect / OAuth2 authentication where the server needs to confirm the authentication keys directly with the provider
- accessing any non-JSON-based APIs (similar to how jnode does it today)

I actually have a need for all 3 of these things. Could be built using a plugin, but it feels like something that would be relatively easy to build in and provide a lot of potential functionality.

**Comment by xyproto** [comment]
With the `httpclient` branch it is now possible to perform GET requests like this:

```lua 
HTTPClient():Get("http://www.guimp.com/")
```

Or by using a variable for the HTTPClient:

```lua 
hc = HTTPClient()
hc:Get("http://www.guimp.com/")
```

Or with URL arguments:

```lua 
HTTPClient():Get("https://jsonplaceholder.typicode.com/comments", {postId=1, id=2})
```

Or with URL arguments and HTTP headers:

```lua 
HTTPClient():Get("https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending", {x=42}, {["X-PoweredBy"]="Bits and bytes"}):match('POWEREDBY.*</td>')
```

Or POST requests like this:

```lua 
HTTPClient():Post("https://jsonplaceholder.typicode.com/posts", {}, {["Content-type"]="application/json; charset=UTF-8"}, JSON({title="foo", body="bar", userId=1}))
```

Does this seem like a somewhat viable approach, or is it too verbose?

**Comment by seansbox** [comment]
I think this is a good approach. The verbosity is a good balance of flexibility and simplicity. Any reason to have to instantiate an object versus just having an httprequest function? Are there any stateful parameters or other methods? Looks like only autonomous function calls.

**Comment by xyproto** [comment]
Added `GET`, `POST` and `DO` as shorthand functions.

Unfortunately, the HTTPClient settings like timing and language seems to be possible to set only once, so I'll have to restructure how the object is stored before this will work.

**Comment by xyproto** [comment]
Closing this issue as fixed, please re-open this issue if there should be further issues with this.
