### ISSUE TITLE
Parity with command-line options and serverconf.lua

### ISSUE THREAD

**Issue by seansbox** [xyproto/algernon#35]
I'm currently using a shell script to execute algernon, because I don't know how to translate the command line options into the serverconf.lua, or know if there even is a way to access some of the command-line flags from the conf file. Here is what I'm using. Would it be possible to have parallel functions in serverconf.lua available which align to these options? Do they already exist but are just not documented? It would great for cross-platform compatibility if I could just use the serverconf.lua and not have to have the launch script.

    #!/bin/bash

    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

    "$DIR/algernon" \
      --dir="$DIR/srv" \
      --boltdb="$DIR/data.bolt" \
      --key="$DIR/key.pem" \
      --cert="$DIR/cert.pem" \
      --dev \
      --autorefresh \
      --cookiesecret="9jc9djcd000dcd"

**Comment by xyproto** [comment]
Thanks for reporting. I wish to use a good Go module that can handle configuration from both configuration files and command line flags, and make sure they stay in sync. It's a bit of work to make this transition, and many of the changes are likely to not be fully backward-compatible, so I'm considering if this should be a feature for Algernon 2 instead.

**Comment by xyproto** [comment]
Moved this to `TODO.md`, for the successor of Algernon.
