### ISSUE TITLE
algernon -l to execute lua script

### ISSUE THREAD

**Issue by Dialga** [xyproto/algernon#40]
Currently algernon does not execute the lua script passed to -l, it would be useful for development if -l runs the lua script or string that's passed to it(- for stdin), much like the lua repl.

**Comment by xyproto** [comment]
I like the idea! Thanks for reporting.

**Comment by xyproto** [comment]
I thought this functionality might be missing, but when I tried it, it worked as expected:

**hello.lua:**

```lua
print("hello")
```

**With Algernon**

```
$ algernon -l hello.lua
Algernon 1.12.5 - 2019-12-08 14:59
hello
Ready
lua> 
```

It is also possible, from the `lua>` prompt in Algernon to run an external file, like this:

```
lua> dofile("hello.lua")
hello
```

Does this fulfill the original feature request, or are there additional functionality that would be interesting to add to Algernon?

**Comment by Dialga** [comment]
Oh, I was trying algernon -l hello with the script without the .lua extension, hence why it wasn't working. The lua repl accepts lua scripts without the .lua extension.

**Comment by xyproto** [comment]
I updated the code in master to also run Lua scripts without the `.lua` extension, when using the `-l` or `--lua` flag.
