### ISSUE TITLE
algernon 1.12.11 failed to build on apple silicon

### ISSUE THREAD

**Issue by chenrui333** [xyproto/algernon#49]
👋  it looks like algernon 1.12.11 failed to build on apple silicon as error log show below:

```
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210102-35928-hbkxt1.sb ruby -W0 -I $LOAD_PATH -- /opt/homebrew/Library/Homebrew/test.rb /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/algernon.rb --verbose
panic: qtls.ClientHelloInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
	github.com/marten-seemann/qtls-go1-15@v0.1.1/unsafe.go:20 +0x1b4
==> curl -sIm3 -o- http://localhost:53111

Error: algernon: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<7>.
```

build error log, https://github.com/Homebrew/homebrew-core/runs/1638106915
relates to https://github.com/Homebrew/homebrew-core/pull/68188

**Comment by xyproto** [comment]
Thanks for reporting!

Does this happen when building with `go build -mod=vendor` or `go build`? The error looks like an error that can also appear when not using the vendored dependencies.

**Comment by xyproto** [comment]
@chenrui333

I added support to Algernon for compiling without QUIC when on `darwin` but not on `amd64` to the `main` branch.

Is there an easy way to check if this would work with the Homebrew recipe above, before making a new release of Algernon?

**Comment by xyproto** [comment]
I created a fix for this, where QUIC support is not included when building for darwin + amd64.

Please re-open this issue if there are further problems with this.

**Comment by chenrui333** [comment]
looks solid in [this PR](https://github.com/Homebrew/homebrew-core/pull/69272), thanks @xyproto!

**Comment by xyproto** [comment]
Great! Thank you, @chenrui333!
