### ISSUE TITLE
redirect() and status() not setting HTTP status?

### ISSUE THREAD

**Issue by deanishe** [xyproto/algernon#5]
I've been trying to get a simple webapp up and running with Algernon, but I can't seem to get the `redirect()` and `status()` Lua functions to work. The problem appears to be that although they set the `Location:` header correctly, they don't set the HTTP status (it's always 200), so no redirect.

Here's `/logout/index.lua`:

```lua
if Username() ~= '' then
    Logout(Username())
end

redirect('http://localhost:3000/login/')
-- status(302)
-- setheader('Location', 'http://localhost:3000/login/')
```

And here's what `httpie` says:

```
# http http://localhost:3000/logout/
HTTP/1.1 200 OK
Content-Length: 63
Content-Type: text/html; charset=utf-8
Date: Tue, 12 Jul 2016 18:41:24 GMT
Location: http://localhost:3000/login/
Server: Algernon 1.0
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

<a href="http://localhost:3000/login/">Moved Permanently</a>.
```

I had a look at the source code, but I couldn't figure it out.

Additionally, I think 301 (Moved Permanently) should probably be changed to 302 (Found). I believe that if you do, say, a 301 redirect from your logout page to your homepage, on subsequent attempts to visit `/logout`, the browser might skip that URL and go directly to `/`.

**Comment by xyproto** [comment]
Thanks for reporting! I'll look into this.

**Comment by deanishe** [comment]
Thanks very much. FWIW, `curl` does follow the redirect (if you use `-L` and it's an absolute URL), but Safari and Chrome don't.

**Comment by xyproto** [comment]
Added a second (optional) parameter to the `redirect()` function, where the HTTP status code can be supplied. It's checked into the master branch.

Does this solve the problem for you?

**Comment by xyproto** [comment]
Also note that the `status` function is special in that it must come before other calls that changes the HTTP output. (It's mentioned briefly in the documentation, but I should really add a test for this that makes Algernon output a warning).

**Comment by deanishe** [comment]
No, that doesn't fix the problem.

Perhaps I've misunderstood something about the way Algernon works (is there something I have to do to prevent *it* sending output?)

A folder containing nothing but `index.lua` with the contents:

```
redirect("https://www.google.com")
```

doesn't work. The `Location` header is set, but the HTTP status is still 200. Same for `status()`.

**Comment by xyproto** [comment]
This index.lua file, will return HTTP status 418:

**index.lua**

```lua
status(418)
print("hello")
```

```bash
http localhost:3000

HTTP/1.1 418 I'm a teapot
Content-Length: 6
Content-Type: text/plain; charset=utf-8
Date: Wed, 13 Jul 2016 17:57:45 GMT
Server: Algernon 1.0
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

hello
```

While this will return 200:

```
print("hello")
status(418)
```

Because the status function call must come first, before any other calls that output anything. This is because of the way Go works in connection with http.

**Comment by xyproto** [comment]
Same thing with the new redirect parameter, the redirect function call has to come before other functions that output text or HTTP headers:

This index.lua file works (for the master branch):

```lua
redirect("http://somewhere", 418)
print("hello")
```

And returns this:

```
HTTP/1.1 418 I'm a teapot
Content-Length: 52
Content-Type: text/html; charset=utf-8
Date: Wed, 13 Jul 2016 18:13:32 GMT
Location: http://somewhere
Server: Algernon 1.0
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

<a href="http://somewhere">I'm a teapot</a>.

hello
```

**Comment by deanishe** [comment]
I figured out why it works for you and not me.

Being a total n00b, I'm running algernon in debug mode. If you use `-d` (or `-e`), the HTTP status is always 200. (A side-effect of the in-browser errors feature?)

Run with debugging off, and everything works swimmingly.

Regarding, `redirect()`, I would suggest changing the second parameter to `permanent bool`. AFAIK, there's only 301, 302 and 307 to choose from, and nobody uses 307. Seem a bit easier than trying to remember whether 301 or 302 is the permanent one.

**Comment by xyproto** [comment]
Yes, this is a bug, the HTTP status commands should work even when in debug mode. Thanks for discovering! Will fix.

Good idea with a bool *permanent* flag! `status` should cover the cases where one wants to set the http status code manually.

**Comment by xyproto** [comment]
* Added a `permanent_redirect` function, that only takes an URL.
* Changed the behavior of the `redirect` function so that it will use code 302 when only given an URL.
* Fixed the problem where HTTP status was not set properly when debug mode was enabled.

Please confirm that it works for you now.

**Comment by deanishe** [comment]
Works like a charm. Thanks very much for the super-fast fix.
