### ISSUE TITLE
Teal Support

### ISSUE THREAD

**Issue by tooolbox** [xyproto/algernon#58]
Might be interesting to support [Teal](https://github.com/teal-language/tl) so that you can have typed lua code.  Would make it easier to build larger, more complex apps with Algernon.

- Looks a little like TypeScript.
- Implemented in pure Lua.
- [Web playground](https://teal-playground.netlify.app/?c=LS0gVGVhbCBzdXBwb3J0cyBhIHNpbXBsZSBmb3JtIG9mIGdlbmVyaWNzIHRoYXQgaXMKLS0gdXNlZnVsIGVub3VnaCBmb3IgZGVhbGluZyBjb2xsZWN0aW9ucyBhbmQgYWxnb3JpdGhtcyB0aGF0Ci0tIG9wZXJhdGUgb3ZlciBhYnN0cmFjdCBkYXRhIHR5cGVzLiBZb3UgY2FuIHVzZSB0eXBlCi0tIHZhcmlhYmxlcyB3aGVyZXZlciBhIHR5cGUgaXMgdXNlZCwgYW5kIHlvdSBjYW4gZGVjbGFyZSB0aGVtCi0tIGluIGJvdGggZnVuY3Rpb25zIGFuZCByZWNvcmRzLiBIZXJlJ3MgYW4gZXhhbXBsZSBvZiBhCi0tIGdlbmVyaWMgZnVuY3Rpb246Cgpsb2NhbCBmdW5jdGlvbiBrZXlzPEssVj4oeHM6IHtLOlZ9KTp7S30KICBsb2NhbCBrcyA9IHt9CiAgZm9yIGssIHYgaW4gcGFpcnMoeHMpIGRvCiAgICB0YWJsZS5pbnNlcnQoa3MsIGspCiAgZW5kCiAgcmV0dXJuIGtzCmVuZAoKbG9jYWwgcyA9IGtleXMoeyBhID0gMSwgYiA9IDIgfSkgLS0gcyBpcyB7c3RyaW5nfQ%3D%3D).
- [VSCode plugin](https://github.com/teal-language/vscode-teal).

*Disclaimer: I am far more experienced with Go, and even somewhat with TS, compared to Lua.*

**Comment by scrumit** [comment]
I looked at teal, it's a single lua file with no dependencies, and a loader
that allows teal modules to be included into lua apps. In theory teal
should be usable with any lua interpreter.

I don't have Algernon installed on a computer nearby and busy doing other
stuff but I'll be using teal for some projects. Static typing is good.

**Comment by xyproto** [comment]
I tried loading `tl.lua` from Algernon, but it didn't quite work:

```lua
lua> local tl = require("tl")
lua> tl.loader()
<string>:1: attempt to index a non-table object(nil)
stack traceback:
        <string>:1: in main chunk
        [G]: ?
```

This could be perhaps be caused by the Lua implementation that Algernon is using.

Either way I believe "the right way" to add support for a language like Teal directly into Algernon would be to use a suitable Go module.

I do wonder what `tl.loader()` has issues with, though.

**Comment by tooolbox** [comment]
> In theory teal should be usable with any lua interpreter.

Indeed.  What interests me would be first-class support, i.e. the option to use `data.tl` instead of `data.lua`, and such things.

> I tried loading tl.lua from Algernon, but it didn't quite work

I noticed your fork is [a few commits behind](https://github.com/xyproto/gopher-lua/compare/master...yuin:master) the original, and specifically [this fix](https://github.com/yuin/gopher-lua/pull/265) which gives a more descriptive error for this problem.  Pulling it in (and maybe other commits?) might help.

> Either way I believe "the right way" to add support for a language like Teal directly into Algernon would be to use a suitable Go module.

I'm curious what you mean by this?  Generally I would agree but since Teal is written in Lua I'm not sure what Go resources would exist to do anything with it.

My thought had been something along the lines of using Teal, I suppose within the GopherLua VM, to compile `.tl` files and the Go side caching them and so on to prevent the compilation overhead on every request.

**Comment by tooolbox** [comment]
Wanted to let you know I've [taken this upstream](https://github.com/yuin/gopher-lua/issues/314) since the problem is not with Algernon.  Once GopherLua supports it, it would be great to see some kind of first-class support for Teal in Algernon.

**Comment by scrumit** [comment]
Apologies for starting this. I’ve commented in GopherLua.

**Comment by xyproto** [comment]
Closing this feature request, for now. Please create a new feature request if adding support for Teal (or another typed language) to Algernon seems to be feasible.

I assume that in many cases it's possible to compile from a typed language down to Lua, and then use Algernon to run the resulting Lua code.

**Comment by tooolbox** [comment]
Thanks, yeah I will revisit this when I can get to it and/or it becomes more feasible.  The GopherLua multi-assignment bug is an annoying blocker that I could work around by forking the Teal compiler but I'd rather not be in that position.

Couple thoughts:

1. I think eventually it would be superb to have first-class Teal support, but it will be a chunk of work to put the Teal compiler into Algernon and figure out a caching strategy for the compiled code.  Could be done, but it's a bit down my priority list.
2. As a next-best option, I'm halfway through writing Teal definitions (like a Typescript definition file) for the Algernon environment.  With these, you can use Teal as a linter to analyze your plain Lua code and warn you about type errors.  Theoretically we could ship the `.d.tl` file with Algernon and have a note about where to get the appropriate IDE plugins.

**Comment by tooolbox** [comment]
As a note I did get the Teal loader working, via `compat52` and tweaking Teal itself to bypass the gopher-lua multi-assignment bug.  By using an appropriate `serverconf.lua` setup, I can `require()` and call a Teal file successfully.

This alone might be a neat feature for Algernon, by embedding these modules in the binary and loading them by default into the Lua VM.  The last step would be figuring out how to process `data.lua`, `index.lua`, `serverconf.lua` and other such files.

The only drawback is that I had to modify `compat52` and `tl.lua` (one line each) so pulling in upstream updates will be annoying, but I have issues open to handle the incompatibilites.

**Comment by xyproto** [comment]
Excellent! Supporting Teal directly is a good goal.

**Comment by scrumit** [comment]
Yay!

**Comment by tooolbox** [comment]
Alright, I figured out running Teal scripts directly and not just requiring Teal modules.

@xyproto any particular preference as to how I embed some Lua files into the Algernon codebase?  I don't want to limit support to Go 1.16 so it will likely be something like https://github.com/go-bindata/go-bindata or https://github.com/markbates/pkger or some such.  Haven't yet reviewed to see what's the best one.  Think I've used go-bindata before.

**Comment by xyproto** [comment]
@tooolbox A homegrown and slightly ghetto solution to avoid the embed feature in Go 1.16 is to base64 encode the data as a string, like here:

 https://github.com/xyproto/algernon/blob/4756020847d3313075884df965721aaeacbf8e81/platformdep/logo_unix.go#L33

It works, though. 🙂

**Comment by xyproto** [comment]
Would Teal still be an interesting addition to Algernon, and does it work with the latest `main` that uses `esbuild`?

**Comment by tooolbox** [comment]
To me, yes, it would be an interesting and worthy addition. The vision I had was writing Algernon apps with autocompletion, some type safety, and editor support in terms of highlighting syntax errors or incorrect types.

I don't know whether the setup I concocted still works with latest `main` but it's not related to `esbuild` since this is the Lua side, not the JS side.

From what I recall:
- My ticket opened on gopher-lua re multi-assignment was never addressed; the maintainer is perhaps busy elsewhere.
- My one-line modifications to Teal and `compat52` did allow them to work in gopher-lua.
- The Teal loader did work and allow it to load `.tl` modules.
- Where things fell down was trying to work around Teal's built-in module caching. This became a messy intersection and I abandoned it.

What I did do instead was run Teal as an incremental in-IDE typechecker, with a definition file for the Algernon functions I cared about. I put these files in my app directory and got some autocompletion going:

```lua
-- tlconfig.lua
return {
	global_env_def = "algernon"
}
```

```lua
-- algernon.d.tl

-- Return the version string for the server.
global version: function(): string

-- Sleep the given number of seconds (can be a float).
global sleep: function(sec: number)

-- Log the given strings as information. Takes a variable number of strings.
global log: function(...: string)

-- Log the given strings as a warning. Takes a variable number of strings.
global warn: function(...: string)

-- Log the given strings as an error. Takes a variable number of strings.
global err: function(...: string)

-- Return the number of nanoseconds from 1970 ("Unix time")
global unixnano: function(): number

-- Convert Markdown to HTML
global markdown: function(data: string): string

-- Set the Content-Type for a page.
global content: function(ct: string)

-- Return the requested HTTP method (GET, POST etc).
global method: function(): string

-- Return the requested URL path.
global urlpath: function(): string

-- Return the HTTP header in the request, for a given key, or an empty string.
global header: function(key: string): string

-- Set an HTTP header given a key and a value.
global setheader: function(key: string, val: string)

global print: function(...: string)

-- Return the HTTP headers, as a table.
global headers: function(): {string:string}

-- Return the HTTP body in the request (will only read the body once, since it's streamed).
global body: function(): string

-- Set a HTTP status code (like 200 or 404). Must be used before other functions that writes to the client!
global status: function(code: number)

-- Serve a file that exists in the same directory as the script. Takes a filename.
global serve: function(filename: string)

-- Serve a Pongo2 template file, with an optional table with template key/values.
global serve2: function(filename: string, args: {string:any} | nil)

-- Return the rendered contents of a file that exists in the same directory as the script. Takes a filename.
global render: function(filename: string): string

-- Return a table with keys and values as given in a posted form, or as given in the URL.
global formdata: function(): {string:string}

-- Return a table with keys and values as given in the request URL, or in the given URL (`/some/page?:7` makes the key `x` with the value `7` available).
global urldata: function(url: string | nil): {string:string}

-- Redirect to an absolute or relative URL. May take an HTTP status code that will be used when redirecting.
global redirect: function(path: string, code: number | nil)

global MSSQL: function(sql: string, conn: string, args: {string:any} | nil): {{string:any}}

global POST: function(url: string, params: {string:string}, headers: {string:string}): string

global GET: function(url: string, params: {string:string}, headers: {string:string}): string

global json: function(any): string
```

Note that I didn't make stubs for every function that Algernon has to offer.

**Comment by tooolbox** [comment]
To summarize:

- The work that I did should allow an Algernon server to `require()` a Teal module from `serverconf.lua` (which is the only place you can really require anything anyway, due to module caching).
- This doesn't help you if you want an `index.tl`.
- Running Teal as an incremental typechecker in your IDE, with a stubs file, gets you some safety.
- The fact that Algernon's `require()` behavior uses the root server directory is at odds with how Lua typically works, and therefore how Teal's typechecking behaves. Progress on https://github.com/xyproto/algernon/issues/76 could improve this situation.

**Comment by tooolbox** [comment]
I have also toyed with the idea of porting the Teal compiler to Go, at least in so far as converting Teal to pure Lua to support the vision of `index.tl`, but I haven't had the time and I'm sure it's not in scope for you :)

**Comment by tooolbox** [comment]
Musing out loud: insofar as adding support for `index.tl` I'm recalling that I was exploring Teal's API for this sort of thing.  It has `process` which reads and executes a file.

The solution may be as simple as:

1. Teal is loaded into the VM on startup.
2. When serving a request, Algernon detects an `index.tl` in the directory.
3. Algernon executes `tl.process("path/to/index.tl")` within the VM.
4. Algernon detects any errors within the VM and logs them or takes whatever action indicated.

Between that, and the general ability to load Teal modules in `serverconf.lua` as mentioned above...that's pretty much all the Teal support you could ask for initially.

Further complications come in re https://github.com/xyproto/algernon/issues/76 and if you're using `require()` to modularize Teal files, because then you need to factor in the Teal loader vs. the built-in loader and devise methods for keeping or breaking cache on those loaders.  But that work could be deferred.

**Comment by xyproto** [comment]
Thanks for the informative answers!

A plan is forming in the back of my head. Could it potentially work out if for instance:

* A flag like `-teal` was added, for letting Algernon load Teal into the Lua VM on startup, and also look for `index.tl`.
* `tl.gen` was used for preparing the teal script, then cache it, and serve the cached version when in "production mode".

?

**Comment by tooolbox** [comment]
Yeah, that sounds about right :)

**Comment by tooolbox** [comment]
I may be able to put together a PR on this shortly.  Will let you know.

**Comment by tooolbox** [comment]
This is now done!
