### ISSUE TITLE
JSON function cannot create arrays

### ISSUE THREAD

**Issue by tooolbox** [xyproto/algernon#65]
The [toJSON function](https://github.com/xyproto/algernon/blob/19fb6993b47924548599a5dd3c0c7d2eeb1a58b4/lua/jnode/jnode.go#L384) uses [Table2InterfaceMap](https://github.com/xyproto/algernon/blob/19fb6993b47924548599a5dd3c0c7d2eeb1a58b4/lua/convert/convert.go#L217) which always creates a map.  It seems like a purely numeric Lua table should be represented in JSON as an array.

Fixing this could also solve other issues such as [pongo2 sorting](https://github.com/xyproto/algernon/issues/57#issuecomment-817064529).

**Comment by xyproto** [comment]
`json({1,2,3,4})` now returns `[1,2,3,4]` instead of `{"1":"1","2":"2","3":"3","4":"4"}`.

I believe this is now fixed. Please re-open this issue if there are still problems with this.
