### ISSUE TITLE
Bug: JSON function ignores boolean values

### ISSUE THREAD

**Issue by tooolbox** [xyproto/algernon#66]
Let's say I want to create this JSON:

```json
{
    "success": true,
    "value": 123
}
```

I would do this:
```lua
-- endpoint.lua
json({
    success = true,
    value = 123,
})
```

But I get this:
```json
{
    "value": 123
}
```

The [conversion](https://github.com/xyproto/algernon/blob/19fb6993b47924548599a5dd3c0c7d2eeb1a58b4/lua/convert/convert.go#L217) doesn't seem to make allowance for boolean values.

**Comment by tooolbox** [comment]
With https://github.com/xyproto/gluamapper/pull/1 in place and pulled into Algernon, this and #65 are resolved by changing [jnode.go](https://github.com/xyproto/algernon/blob/main/lua/jnode/jnode.go#L401) to have this:

```go
		//
		// NOTE:
		//   JSON keys in maps are always strings!
		//   See: https://stackoverflow.com/questions/24284612/failed-to-json-marshal-map-with-non-string-keys
		//

		// Convert the Lua table to a map or slice that can be used when converting to JSON
		// (map[string]interface{} or []interface{})
		mapinterface := gluamapper.ToGoValue(table, gluamapper.Option{
			NameFunc: func(s string) string {
				return s
			},
		})

		// ...
```

I'd make a PR, but gluamapper should change first.

**Comment by xyproto** [comment]
Tested and confirmed that it works.

`json({success=true,value=123})` now returns the correct value.

Thanks! I also added you to the Algernon project with full permissions.

Feel free to modify or improve anything.

**Comment by tooolbox** [comment]
Awesome!  Yeah I saw your invite & accepted, thanks very much.  I have a couple more improvements I've done locally that I will upstream as soon as I have the time.
