### ISSUE TITLE
Bug: Debug mode breaks redirect()

### ISSUE THREAD

**Issue by tooolbox** [xyproto/algernon#67]
Running Algernon with `--dev` enables debug mode, which [buffers Lua output](https://github.com/xyproto/algernon/blob/19fb6993b47924548599a5dd3c0c7d2eeb1a58b4/engine/handlers.go#L265) to allow pretty-printed error pages.

Unfortunately this breaks the `redirect()` Lua function.  The browser gets a 302 response but doesn't redirect.  If you have a GET request and don't otherwise output anything, Go will [add a "Found" hyperlink](https://go.googlesource.com/go/+/go1.16.3/src/net/http/server.go#2178) to the location you specified, but this is not adequate.

**Comment by xyproto** [comment]
Yes, this is an issue.

**Comment by tooolbox** [comment]
I believe having debug mode also breaks `setheader()`.

**Comment by tooolbox** [comment]
Also seems to break setting cookies such as the username cookie.

I'm wondering if we're using [`httptest.ResponseRecorder`](https://golang.org/pkg/net/http/httptest/#ResponseRecorder) incorrectly.  We are [accessing its HeaderMap](https://github.com/xyproto/algernon/blob/19fb6993b47924548599a5dd3c0c7d2eeb1a58b4/utils/recorders.go#L13) but the docs say that field is deprecated and you should use `recorder.Result().Header` instead.  I'll try it out.

**Comment by tooolbox** [comment]
Alright, the problem is calling `w.WriteHeader` before copying the headers.  Per the docs, `Changing the header map after a call to WriteHeader (or Write) has no effect unless the modified headers are trailers.`

I don't really get why there's a `FutureStatus` since we're buffering the HTTP responses anyway.  Hm, I suppose when debug mode is off, there's no buffering.

I'll put together a PR but I'd like you to look at it @xyproto before I merge it since it will potentially affect parts of the system I haven't grokked yet.
