### ISSUE TITLE
Problem serving files with % in filename

### ISSUE THREAD

**Issue by Dialga** [xyproto/algernon#73]
For example hello%world.txt results in 400 Bad Request and hello%20world.txt results in File not found: ./hello world.txt.
Expected result is that these files are served correctly.

**Comment by xyproto** [comment]
Thanks for reporting! I'll look into this.

**Comment by xyproto** [comment]
Confirmed. Serving "hello%world.txt" does not work.

**Comment by Dialga** [comment]
Just bumping.

Is this a WONTFIX?

**Comment by xyproto** [comment]
No, I'm still planning to fix this. Pull requests are welcome.

**Comment by xyproto** [comment]
I added URL encoding of the links in the directory listings.

```
touch 'hello%world.txt'
algernon -x .
```

And then clicking `hello%world.txt` now works in `main`.
