### ISSUE TITLE
Consider Esbuild Integration

### ISSUE THREAD

**Issue by tooolbox** [xyproto/algernon#77]
[Esbuild](https://github.com/evanw/esbuild) is a pure-Go JS bundler with syntax lowering features.

1. One of the features of Algernon is JSX transformation, using [goja-babel](https://github.com/jvatic/goja-babel).  Replacing this with Esbuild could see dramatic performance improvements.
2. By integrating Esbuild into Algernon, it could do on-the-fly (or cached) processing, including bundling, typescript stripping, the aforementioned JSX transforms, and lowering to ES6.

I could see general integration being achieved in a few ways:

- Exposing the Esbuild API to Lua so you can call it from handler code.
- Perhaps, in the matter of `.lua` or `.tmpl`, a `.esbuild` file extension which signals Algernon to use it as an entry point.
- A local `config.esbuild` file which tells Algernon how to configure Esbuild for a particular directory.

**Comment by xyproto** [comment]
I support this idea!

**Comment by xyproto** [comment]
I created a `jsx` branch that switches from goja-babel to esbuild. It feels really fast, after running a few simple tests.

https://github.com/xyproto/algernon/tree/jsx
