### ISSUE TITLE
Go 1.14, 1.15 Broken

### ISSUE THREAD

**Issue by tooolbox** [xyproto/algernon#78]
https://github.com/xyproto/algernon/commit/6a3c23d6722c393d99171f1aee84d6f91fdcbcf8 broke Go 1.14 and 1.15 because upgrading to the latest goja-babel includes https://github.com/jvatic/goja-babel/commit/5351c627260484c1a9e0e4140a15f2af55d0e38c which uses `embed`, introduced in Go 1.16.  Suggest rolling back that particular dependency to continue to support 1.14 and 1.15.

**Comment by tooolbox** [comment]
Started to make a PR but since I'm not in front of a Real Computer at the moment, not working out.  @xyproto I plan to merge #79 (no need for a review particularly) but would like to get this fixed because it's tanking CI.

**Comment by xyproto** [comment]
Thanks! I downgraded goja-babel.
