### ISSUE TITLE
reading directories

### ISSUE THREAD

**Issue by mischief** [xyproto/algernon#8]
it is desirable to be able to read entries of directories for generating e.g. menus or custom directory listings.

i can send a PR for a simple implementation i came up with, but would you prefer something else?

```diff
diff --git a/basic.go b/basic.go
index e33fdef..265fdd3 100644
--- a/basic.go
+++ b/basic.go
@@ -99,6 +99,32 @@ func exportBasicSystemFunctions(L *lua.LState) {
 		return 1 // number of results
 	}))
 
+	L.SetGlobal("ls", L.NewFunction(func(L *lua.LState) int {
+		cwd, _ := os.Getwd()
+		dir := path.Clean(path.Join(cwd, L.ToString(1)))
+		d, err := os.Open(dir)
+		if err != nil {
+			L.RaiseError("failed to open %q: %v", err)
+		}
+		fi, err := d.Readdir(0)
+		if err != nil {
+			d.Close()
+			L.RaiseError("failed to read %q: %v", err)
+		}
+
+		luaTable := L.NewTable()
+		for _, f := range fi {
+			fit := L.NewTable()
+			L.RawSet(fit, lua.LString("name"), lua.LString(f.Name()))
+			L.RawSet(fit, lua.LString("size"), lua.LNumber(f.Size()))
+			L.RawSet(fit, lua.LString("dir"), lua.LBool(f.IsDir()))
+
+			luaTable.Append(fit)
+		}
+		L.Push(luaTable)
+		return 1 // number of results
+	}))
+
 }
 
 // Make functions related to HTTP requests and responses available to Lua scripts.
```

**Comment by xyproto** [comment]
Tested your implementation and it works great here. Please send a PR and I will merge it.

**Comment by mischief** [comment]
hm, it seems there's no straightforward way to read and write plain files in lua either.

do you think it would be useful to have something like lua's io.open/file?

**Comment by xyproto** [comment]
Yes, the Lua io functions are already available. It's used in [one of the samples](https://github.com/xyproto/algernon/blob/master/samples/prettify/index.lua).

But I fully agree that a less verbose method would be better.

`run("cat filename")` should work too, but that's a hack.

Perhaps streamlined functions for querying a selection of commonly used file types could be more useful? Perhaps these: xml, yaml, json, cvs and sqlite?

**Comment by mischief** [comment]
ahh, i see. didn't realize io is already done by gopher-lua. thanks for pointing that out :)
