### ISSUE TITLE
Incorrect Mimetype for Wasm Files

### ISSUE THREAD

**Issue by tooolbox** [xyproto/algernon#82]
When serving a `.wasm` with static file serving, the content type is `application/wasm; charset=utf-8` which breaks `WebAssembly.instantiateStreaming`.  [This](https://github.com/jfhbrook/node-ecstatic/issues/220) was all I could find on it so far.

Not sure where this is coming from.

**Comment by tooolbox** [comment]
Got it, using `mimereader` with `utf8` as `true` [here](https://github.com/xyproto/algernon/blob/19fb6993b47924548599a5dd3c0c7d2eeb1a58b4/engine/mime.go#L9) which apparently adds `;charset=utf-8` [per this](https://github.com/xyproto/mime/blob/master/mime.go#L65).  @xyproto would you mind popping a fix on this one?

More generally, I'm not familiar enough with web standards to know what's correct and what's not to add `charset=utf-8`.  Is that appropriate for something like `image/jpg`?

**Comment by xyproto** [comment]
One of the design principles for Algernon is to use UTF-8 **everywhere**, whenever it is humanly possible. I guess `;charset=utf-8` does not make sense for `image/jpg` and would just be ignored if appended to the mimetype, though.

**Comment by xyproto** [comment]
I believe this is now fixed in the `main` branch. Please test.
