### ISSUE TITLE
Enhancement: Respect Manually Set Content-Type

### ISSUE THREAD

**Issue by tooolbox** [xyproto/algernon#83]
Currently the server will override a manually-set `Content-Type` header.  I think it would be better to leave it alone if one has been set such as with `setheader("Content-Type", "blah")` and otherwise apply the appropriate logic.

**Comment by xyproto** [comment]
Thanks for reporting.

I tried to reproduce this with an `index.lua` file with these two lines:

```lua
setheader("Content-Type", "image/png")
print("test")
```

When serving this with Algernon and loading the page in Firefox, the browser was thoroughly confused and believed that this was a PNG image. The header was not overwritten.

Do you have an example or a way to reproduce the issue?

**Comment by xyproto** [comment]
No worries. Thanks for the reply.

Please re-open this issue, or file a new one, if you should re-encounter this problem.
