### ISSUE TITLE
website certificate expired

### ISSUE THREAD

**Issue by basaran** [xyproto/algernon#85]
just wanted to let you know. I hope everthing is well and you didn't abandon this awesome piece of software.

**Comment by xyproto** [comment]
Thanks for reporting the issue and for the kind words!

I'll look into updating the certificate.

**Comment by xyproto** [comment]
I added Let's Encrypt support to Algernon and will fix the web certificate next week.

**Comment by basaran** [comment]
and the good just got better)

**Comment by xyproto** [comment]
Let's Encrypt has been added to master and https://algernon.roboticoverlords.org/ is now served using this feature, with certificates from Let's Encrypt.
