### ISSUE TITLE
Please cut a new release with go 1.17 support 

### ISSUE THREAD

**Issue by roopakv** [xyproto/algernon#87]
Please cut a new release to unblock https://github.com/Homebrew/homebrew-core/pull/83413

The commit to include is here: https://github.com/xyproto/algernon/pull/86

**Comment by xyproto** [comment]
The commit was merged. I'm using Go 1.17 on my system, and Algernon builds fine here. Does it look good on your side too?

**Comment by roopakv** [comment]
@xyproto yeah it looks good locally, but we cant test with homebrew till there is a new release :)

**Comment by xyproto** [comment]
1.12.14 was just released. Thanks for the notification!
