### ISSUE TITLE
Build failing for Android

### ISSUE THREAD

**Issue by MrAdityaAlok** [xyproto/algernon#89]
When building Algernon version: `1.12.14`  for Android, build fails with  following error 
```
# github.com/lib/pq
vendor/github.com/lib/pq/user_posix.go:12:6: userCurrent redeclared in this block
/home/builder/.termux-build/algernon/build/src/github.com/xyproto/algernon/vendor/github.com/lib/pq/user_other.go:7:29:
previous declaration
```
Go version:  `1.71.1`

**Comment by xyproto** [comment]
Thanks for reporting. Algernon does not support Android yet, but if the issue in github.com/lib/pq is fixed, I would be happy to update the dependencies.
