### ISSUE TITLE
Any plan for reverse proxy function support?

### ISSUE THREAD

**Issue by leopku** [xyproto/algernon#93]
Thanks for this awesome project firstly.

Does there any plan for proxy function support?

**Comment by xyproto** [comment]
Not yet. What type of proxy are you thinking of? SOCKs5? A reverse proxy? Is there a specific use case you have in mind?

**Comment by leopku** [comment]
> Not yet. What type of proxy are you thinking of? SOCKs5? A reverse proxy? Is there a specific use case you have in mind?

I mean reverse proxy.

If `algernon` support reverse proxy, I can only run `algernon` in many case. Otherwise I need running `nginx` or `caddy` in front of `algernon`.

**Comment by xyproto** [comment]
This is a great idea. There are no specific plans for it right now, but I might find time for it, or someone may contribute code.

**Comment by leopku** [comment]
I will dig into the source code of `algernon` tomorrow. And after that hope I can estimate whether I can finish this function.

**Comment by linkerlin** [comment]
> I'm now ready for a reverse proxy with go and built-in libraries.
> 
> But I confused how to add and read reverse proxy configuration infomations.
> 
> Any advice?
Add some-functions to LuaState, using serverconf.lua for the reverse-proxy configuration.

**Comment by xyproto** [comment]
This feature is now in place.
